export const FETCH_FORM = 'FETCH_FORM';
export const FETCH_FORM_SUCCESS = 'FETCH_FORM_SUCCESS';
export const FETCH_FORM_FAILED = 'FETCH_FORM_FAILED';
export const CHANGE_FORM_VALUE = 'CHANGE_FORM_VALUE';
