export const FETCH_ANALYTICS = 'FETCH_ANALYTICS';
export const FETCH_ANALYTICS_SUCCESS = 'FETCH_ANALYTICS_SUCCESS';
export const FETCH_ANALYTICS_FAILED = 'FETCH_ANALYTICS_FAILED';
export const GOT_UPDATED_ANALYTICS = 'GOT_UPDATED_ANALYTICS';
export const WATCH_ANALYTICS = 'WATCH_ANALYTICS';
